version: '3'
services:
  server: 
    # will build ./docker/server/Dockerfile
    build: 
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
     - "9000:9000"
  user:
    # will build ./docker/user/Dockerfile
    build: 
      context: .
      dockerfile: docker/user/Dockerfile
    ports:
      - "3000:3000"